// Server-only: monthly per-person salary history.
// Excel-style: members × months grid.

import "server-only";
import fs from "node:fs/promises";
import path from "node:path";

const FILE = path.join(process.cwd(), "data", "salary-history.json");

export type MemberStatus = "active" | "resigned" | "realigned";

export type Member = {
  name: string;
  status: MemberStatus;
  startMonth: string;          // "2024-05"
  endMonth?: string | null;    // null = still employed
  // monthly cost keyed by "YYYY-MM"; missing keys = no payment that month
  monthly: Record<string, number>;
};

export type SalaryStore = {
  updatedAt: string | null;
  updatedBy: string | null;
  // ordered list of months present in the dataset, e.g. "2024-05" → "2026-12"
  months: string[];
  members: Member[];
};

/** Default seed — May 2024 → December 2024, taken directly from the YAI Costing 2024 sheet. */
export const SEED_SALARY_STORE: SalaryStore = {
  updatedAt: null,
  updatedBy: null,
  // Months are auto-generated by readSalaryStore() from May 2024 → today, then merged
  // with any extras a user pre-saved beyond today. This array is just a seed anchor.
  months: ["2024-05"],
  members: [
    // Bonus pool — compensation, not an expense. Fill in for any month a bonus was paid.
    { name: "Bonus pool (year-end / milestones)", status: "active", startMonth: "2024-05", monthly: {} },

    // ─── Original 2024 cohort (renamed to full names) ─────────────────────
    // May 2026 cells below = NEW base + score-based bonus. Bonus breakdown:
    //   Daly $180, Dilan $300, Rich $170, Virot $170, Samnang $150, Seangleng $100,
    //   Yasomi $149, Alen $105, Chhay $110, Chetra $110, Khun $80, Menghorng $100,
    //   Sam $92, Phanny $90, Sophy/Sokhim/Thida/Noch/Michael/Heang $0.
    //   Total May 2026 bonus pool = $1,906.
    // Peang Sereysothirich = "Rich" (alias). Was a duplicate row before — merged into one.
    { name: "Peang Sereysothirich",       status: "active", startMonth: "2024-05", monthly: { "2024-05": 398.23, "2024-06": 451.31, "2024-07": 433.62, "2024-08": 504.38, "2024-09": 536.69, "2024-10": 547.46, "2024-11": 515.00, "2024-12": 525.92, "2026-01": 766.96, "2026-02": 777.30, "2026-03": 844.35, "2026-04": 1081.00, "2026-05": 1120.00 } },
    { name: "Van Virot",                  status: "active", startMonth: "2024-05", monthly: { "2024-05": 327.46, "2024-06": 433.62, "2024-07": 415.92, "2024-08": 515.15, "2024-09": 558.23, "2024-10": 547.46, "2024-11": 548.00, "2024-12": 547.46, "2026-01": 866.96, "2026-02": 860.02, "2026-03": 861.02, "2026-04": 1040.58, "2026-05": 1120.00 } },
    { name: "DILAN LAKSHITHA LAKMAL",     status: "active", startMonth: "2024-05", monthly: {
      "2024-05": 1000.00, "2024-06": 1000.00, "2024-07": 1000.00, "2024-08": 1000.00, "2024-09": 1000.00, "2024-10": 1000.00, "2024-11": 1000.00, "2024-12": 1000.00,
      "2025-01": 1500.00, "2025-02": 1500.00, "2025-03": 1500.00, "2025-04": 1500.00, "2025-05": 1500.00, "2025-06": 1500.00, "2025-07": 1500.00, "2025-08": 1500.00, "2025-09": 1500.00, "2025-10": 1500.00, "2025-11": 1500.00, "2025-12": 1500.00,
      "2026-01": 1429.46, "2026-02": 1520.00, "2026-03": 1540.00, "2026-04": 2164.70, "2026-05": 2150.00,
    } },
    { name: "Keo Samnang",                status: "active", startMonth: "2024-07", monthly: { "2024-07":  22.19, "2024-08": 460.15, "2024-09": 460.15, "2024-10": 469.00, "2024-11": 481.00, "2024-12": 469.00, "2026-01": 781.42, "2026-02": 731.50, "2026-03": 761.02, "2026-04":  960.46, "2026-05": 1000.00 } },
    { name: "Visal",                      status: "active", startMonth: "2024-08", monthly: { "2024-08": 216.81, "2024-09": 460.15, "2024-10": 469.00, "2024-11": 471.92, "2024-12": 460.00 } },
    { name: "SAMPATH YASOMI",             status: "active", startMonth: "2024-09", monthly: { "2024-09": 511.50, "2024-10": 700.00, "2024-11": 700.00, "2024-12": 700.00, "2026-01": 716.00, "2026-02": 720.00, "2026-03": 740.00, "2026-04":  873.83, "2026-05":  949.00 } },
    { name: "Sreyleak",                   status: "active", startMonth: "2024-07", monthly: { "2024-07": 119.25, "2024-08": 184.50, "2024-09": 223.50, "2024-10": 207.75, "2024-11": 309.00, "2024-12": 369.00 } },
    { name: "Sobon Menghorng",            status: "active", startMonth: "2024-07", monthly: { "2024-07":  65.25, "2024-08": 132.00, "2024-09": 115.50, "2024-10":  78.00, "2024-11":  52.50, "2024-12":  44.25, "2026-01": 517.02, "2026-02": 451.35, "2026-03": 511.02, "2026-04":  580.21, "2026-05":  625.00 } },
    { name: "Set Sophy",                  status: "active", startMonth: "2024-07", monthly: { "2024-07":  65.25, "2024-08": 132.00, "2024-09": 115.50, "2024-10": 117.75, "2024-11":  57.00, "2024-12": 159.00, "2026-01": 526.62, "2026-02": 510.35, "2026-03": 481.19, "2026-04":  481.50, "2026-05":  500.00 } },
    { name: "Chhang Mengchhay",           status: "active", startMonth: "2024-08", monthly: { "2024-08": 143.25, "2024-09": 189.00, "2024-10": 157.50, "2024-11": 214.00, "2024-12": 345.00, "2026-01": 556.10, "2026-02": 505.50, "2026-03": 517.40, "2026-04":  692.60, "2026-05":  685.00 } },
    { name: "Chhim Seangleng",            status: "active", startMonth: "2024-08", monthly: { "2024-08": 103.50, "2024-09": 189.75, "2024-10": 168.75, "2024-11": 238.00, "2024-12": 294.00, "2026-01": 507.05, "2026-02": 490.78, "2026-03": 501.08, "2026-04":  613.90, "2026-05":  700.00 } },
    { name: "Proeurng Sokhim",            status: "active", startMonth: "2024-08", monthly: { "2024-08":  28.50, "2024-09": 122.25, "2024-10": 102.00, "2024-11": 133.50, "2024-12": 223.50, "2026-01": 428.60, "2026-02": 414.20, "2026-03": 431.02, "2026-04":  484.09, "2026-05":  420.00 } },
    { name: "Voun Thida",                 status: "active", startMonth: "2024-09", monthly: { "2024-09": 115.50, "2024-10": 108.00, "2024-11": 132.00, "2024-12": 194.25, "2026-01": 445.80, "2026-02": 431.00, "2026-03": 431.02, "2026-04":  496.02, "2026-05":  420.00 } },
    { name: "Keomhieng",                  status: "realigned", startMonth: "2024-09", endMonth: "2024-11", monthly: { "2024-09": 107.25, "2024-10": 61.50, "2024-11": 59.25 } },
    { name: "Phoumen",                    status: "resigned",  startMonth: "2024-08", endMonth: "2024-08", monthly: { "2024-08": 192.00 } },
    { name: "Yoem Chetra",                status: "active", startMonth: "2024-09", monthly: { "2024-09":  97.50, "2024-10":  90.00, "2024-11": 108.75, "2024-12": 128.00, "2026-01": 440.09, "2026-02": 550.42, "2026-03": 539.21, "2026-04":  638.62, "2026-05":  685.00 } },
    { name: "Koem Chichhorng",            status: "active", startMonth: "2024-10", monthly: { "2024-10":  78.00, "2024-11": 278.80, "2024-12": 422.00, "2026-01": 552.10, "2026-02": 525.90, "2026-03": 525.60, "2026-04":  570.70 } },
    { name: "Vannara",                    status: "active", startMonth: "2024-11", monthly: { "2024-11":  78.00, "2024-12": 331.00 } },
    { name: "Phallin",                    status: "active", startMonth: "2024-12", monthly: { "2024-12": 123.00 } },

    // ─── New 2025 / 2026 joiners (appear in Jan 2026 sheet) ──────────────
    { name: "Pich Daly",                  status: "active", startMonth: "2025-01", monthly: { "2026-01": 929.00, "2026-02": 923.00, "2026-03": 923.02, "2026-04": 1140.25, "2026-05": 1155.00 } },
    { name: "Sin Khon",                   status: "active", startMonth: "2025-01", monthly: { "2026-01": 401.13, "2026-02": 410.35, "2026-03": 378.94, "2026-04":  495.84, "2026-05":  530.00 } },
    { name: "Ton Noeun",                  status: "active", startMonth: "2025-01", monthly: { "2026-01": 467.83, "2026-02": 461.50, "2026-03": 471.02, "2026-04":  471.02 } },
    { name: "Koem Phanny",                status: "active", startMonth: "2025-01", monthly: { "2026-01": 469.84, "2026-02": 401.16, "2026-03": 454.60, "2026-04":  562.39, "2026-05":  540.00 } },
    { name: "Dot Sreynoch",               status: "active", startMonth: "2025-01", monthly: { "2026-01": 445.80, "2026-02": 430.35, "2026-03": 431.02, "2026-04":  496.22, "2026-05":  420.00 } },
    { name: "Van Phanith",                status: "active", startMonth: "2025-01", monthly: { "2026-01": 410.19, "2026-02": 394.31, "2026-03": 394.98, "2026-04":  439.55 } },
    { name: "Young Sengheang",            status: "active", startMonth: "2025-01", monthly: { "2026-01": 437.00, "2026-02": 404.48, "2026-03": 414.21, "2026-04":  473.81, "2026-05":  420.00 } },

    // ─── May 2026 onboards (raise sheet has them but not Jan-Apr) ─────────
    { name: "Alen",                       status: "active", startMonth: "2026-05", monthly: { "2026-05": 705.00 } },
    { name: "Sam",                        status: "active", startMonth: "2026-05", monthly: { "2026-05": 592.00 } },
    { name: "Michael",                    status: "active", startMonth: "2026-05", monthly: { "2026-05": 400.00 } },
  ],
};

const START_YEAR = 2024;
const START_MONTH = 5; // May 2024 — first month of operations

/** Generate "YYYY-MM" strings from May 2024 up to the current real-world month (inclusive). */
function monthsUpToToday(): string[] {
  const now = new Date();
  const endYear = now.getFullYear();
  const endMonth = now.getMonth() + 1; // 1-12
  const out: string[] = [];
  let y = START_YEAR;
  let m = START_MONTH;
  while (y < endYear || (y === endYear && m <= endMonth)) {
    out.push(`${y}-${String(m).padStart(2, "0")}`);
    m++;
    if (m > 12) { m = 1; y++; }
  }
  return out;
}

/** Merge auto-generated months (May 2024 → today) with any extras a user pre-saved past today. */
function buildMonths(stored: string[] | undefined): string[] {
  const base = monthsUpToToday();
  if (!stored?.length) return base;
  const merged = new Set([...base, ...stored.filter((m) => /^\d{4}-\d{2}$/.test(m))]);
  return Array.from(merged).sort();
}

export async function readSalaryStore(): Promise<SalaryStore> {
  try {
    const text = await fs.readFile(FILE, "utf-8");
    const parsed = JSON.parse(text) as SalaryStore;
    return {
      updatedAt: parsed.updatedAt ?? null,
      updatedBy: parsed.updatedBy ?? null,
      months: buildMonths(parsed.months),
      members: parsed.members ?? SEED_SALARY_STORE.members,
    };
  } catch {
    return {
      ...SEED_SALARY_STORE,
      months: buildMonths(SEED_SALARY_STORE.months),
    };
  }
}

export async function writeSalaryStore(store: SalaryStore): Promise<void> {
  await fs.mkdir(path.dirname(FILE), { recursive: true });
  await fs.writeFile(FILE, JSON.stringify(store, null, 2), "utf-8");
}
